"""add attio record id to lead

Revision ID: 486219e0ada9
Revises: c5339b83a387
Create Date: 2026-05-19 18:47:48.049363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486219e0ada9'
down_revision: Union[str, Sequence[str], None] = 'c5339b83a387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attio_record_id', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('uq_leads_attio_record_id', ['attio_record_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('uq_leads_attio_record_id', type_='unique')
        batch_op.drop_column('attio_record_id')

    # ### end Alembic commands ###
